### ISSUE TITLE
Error when calling in Command Palette

### ISSUE THREAD

**Issue by bhuddleston** [technocoreai/SublimeExternalCommand#6]
I just installed Sublime Text 3 and have been setting up my environment.  I installed `SublimeExternalCommand` and it works when called from *Selection -> Filter Through Command*, but when I try to call it from the Command Palette <kbd>cmd</kbd><kbd>shift</kbd><kbd>p</kbd> I get this error:

>Error loading syntax file "Packages/SublimeExternalCommand/external_command.hidden-tmLanguage": Unable to open Packages/SublimeExternalCommand/external_command.hidden-tmLanguage

Once I click *OK* it continues to work fine, and subsequent calls from the Command Palette work well (until I restart Sublime Text 3 again).

**Comment by technocoreai** [comment]
I'm still using ST2, and the ST3 version is maintained [here](https://github.com/greneholt/SublimeExternalCommand). Please resubmit the issue to that repository.
